name: Testing app

on:
  push:
    branches:
      - '**'  # triggers on any branch

jobs:
  run-on-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database
        run: |
          python <<EOF
            from app import db, app
            with app.app_context():
            db.create_all()
            EOF

      - name: Run tests
        run: pytest  